### ISSUE TITLE
CLI handling of Trigger parameters vs Feed parameters

### ISSUE THREAD

**Issue by eweiter** [apache/openwhisk-cli#293] opened 2018-05-03 20:14 UTC
This issue is the culmination of discussions and two other issues that were opened, #289 & #290 .

A proposal was talked about for how to handle the above two issues as well as the third issue, the issue of parameters during the creation of a Trigger, and so I wanted to consolidate everything down into a single issue. 

This issue tackles three deficiencies currently in the CLI:
1) Ability to create a Trigger with Trigger parameters and/or Feed parameters
2) Ability to update a Trigger that has a Feed attached, and update that Trigger's Trigger parameters and/or Feed parameters
3) Ability to get a Trigger that has a Feed attached, and get that Trigger's Trigger parameters and/or Feed parameters

The functionality of the CLI should operate as follows for all three cases: (showing CLI calls as if they were following the proposal that will be mentioned below):
1) `wsk trigger create myTrigger --feed whisk.system/alarms/alarm -p cron "* * * * *" -p otherParam myParam.
Trigger is created with the "cron" param that is sent to the Feed provider, Trigger has the "otherParam" param stored in its "parameters" property.

2) `wsk trigger update myTrigger -p cron "* h/2 * * *" -p newParam "0"`
Trigger sends "cron" param to Feed provider to update it's params, Trigger updates its "parameters" property and stores "newParam" 

3) `wsk trigger get myTrigger`
Result returned will contain the Feed params and the Trigger params. 
So you will see Feed having "cron" and Trigger having "otherParam" and "newParam"

The proposal for how to accomplish this is the following:
- The CLI would have to query the Feed Action before creating & updating a Trigger. 
- It would like at the Feed Action for what parameters are required and optional.  
- It would digest the list of parameters the user is supplying to either the "create" or "update" command and determine if they are a Feed parameter or a Trigger parameter.
- It will send Feed parameters off with the Feed CRUD actions and it will create/update the Trigger object according through the Trigger api calls. 

For instance, the alarms/alarm Feed Action has the following configuration:
```
{
    "namespace": "whisk.system",
    "name": "alarms",
    "version": "0.0.135",
    "publish": true,
    "annotations": [
        {
            "key": "description",
            "value": "Alarms and periodic utility"
        },
        {
            "key": "parameters",
            "value": [
                {
                    "name": "trigger_payload",
                    "required": false
                }
            ]
        }
    ],
    "parameters": [
        {
            "key": "apihost",
            "value": "openwhisk.ng.bluemix.net"
        },
        {
            "key": "trigger_payload",
            "value": ""
        }
    ],
    "binding": {},
    "feeds": [
      ...
        {
            "name": "alarm",
            "version": "0.0.135",
            "annotations": [
                {
                    "key": "feed",
                    "value": true
                },
                {
                    "key": "description",
                    "value": "Fire trigger when alarm occurs"
                },
                {
                    "key": "parameters",
                    "value": [
                        {
                            "name": "cron",
                            "required": true
                        },
                        {
                            "name": "startDate",
                            "required": false
                        },
                        {
                            "name": "stopDate",
                            "required": false
                        }
                    ]
                },
                {
                    "key": "exec",
                    "value": "nodejs:6"
                }
            ]
        }
    ]
}
```
So we see through the Annotations and Parameters properties that "trigger_payload" is optional, and we see in the "alarm" Action, "cron" is required, "startDate" is optional, "stopDate" is optional. 

All of these would be reserved and so if the CLI detects any of them it sends them to the feed.  Else it puts them in the Triggers parameters property

**Comment by steven7dong** [comment] 2019-12-31 15:55
@eweiter @mdeuser @dubee @csantanapr The problem lies in our cli argument digestion. Because both trigger param and feed param are mixed together using --param KEY VALUE and we do not query the feed parameters for a feed package, we don't know which parameter is for trigger and which is for feed param. I would suggest introducing a new parameter called --feed-param (-fp) so that trigger param and feed param could be properly distinguished.

**Comment by steven0711dong** [comment] 2019-12-31 16:19
@eweiter @mdeuser @dubee @csantanapr The problem lies in our cli argument digestion. Because both trigger param and feed param are mixed together using --param KEY VALUE and we do not query the feed parameters for a feed package, we don't know which parameter is for trigger and which is for feed param. I would suggest introducing a new parameter called --feed-param (-fp) so that trigger param and feed param could be properly distinguished.

**Comment by rabbah** [comment] 2019-12-31 18:29
@steven0711dong aren't all parameters passed on to a feed when you using `trigger create --feed`?

**Comment by steven0711dong** [comment] 2019-12-31 19:02
@rabbah `trigger create --feed` only indicates the feed action. Feed parameters are passed in using --param FEEDKEY FEEDVALUE. Trigger parameters are also passed in using --param TRIGGERKEY TRIGGERVALUE. The problem is cli argument digestion does not distinguish the two.

**Comment by steven0711dong** [comment] 2020-02-25 19:09
https://github.com/apache/openwhisk-cli/pull/479#event-3070360724
This issue has been handled in the above PR. I cannot close the issue.

**Closed** 2020-04-15 22:48 UTC
